"""expand lab roles and add compensation

Revision ID: 0a98b5af9357
Revises: e9d236d16a67
Create Date: 2026-05-16 16:32:06.881189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a98b5af9357'
down_revision = 'e9d236d16a67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_memberships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compensation_type', sa.Enum('project_salary', 'research_grant', name='compensationtype'), nullable=True))
        batch_op.add_column(sa.Column('compensation_value', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('ceo', 'engineering_manager', 'project_manager', 'research_manager', 'tech_lead', 'engineer', 'researcher', 'staff', name='labrole'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_memberships', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('ceo', 'engineering_manager', 'project_manager', 'research_manager', 'tech_lead', 'engineer', 'researcher', 'staff', name='labrole'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.drop_column('compensation_value')
        batch_op.drop_column('compensation_type')

    # ### end Alembic commands ###
