"""empty message

Revision ID: 2d2babd5edd6
Revises: f1a2b3c4d5e6
Create Date: 2026-05-16 22:12:17.765057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d2babd5edd6'
down_revision = 'f1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_members_cpf'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_members_cpf'), ['cpf'])

    # ### end Alembic commands ###
